# my global config
global:
  scrape_interval: 100s 


scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "website"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8000"]
